project-init:
	npm init

project-webpack:
	npm install -D webpack webpack-cli

project-webpack-plugins:
	npm install -D html-webpack-plugin
	npm install -D clean-webpack-plugin

build-dev:
	npm run dev

build-prod:
	npm run prod
