version: "3.7"
services:
    frontend:
        build:
            context: frontend/docker/development/nginx
        ports:
            -   "${PORT_FRONT}:80"
        volumes:
            -   ./frontend:/app
    api:
        build:
            context: api/docker
            dockerfile: development/nginx/Dockerfile
        ports:
            -   "${PORT_API}:80"
        volumes:
            - ./api:/app
        depends_on:
            - api-php-fpm

    api-php-fpm:
        build:
            context: api/docker
            dockerfile: development/php-fpm/Dockerfile
        volumes:
            - ./api:/app
